### ISSUE TITLE
How can I use it with pm2?

### ISSUE THREAD

**Issue by arden** [zeit/micro#93]

**Comment by leo** [comment]
@arden Could you please convert this issue to english? 😄

**Comment by bnjmnt4n** [comment]
@leo basically the question is how to use it together with pm2.

**Comment by amio** [comment]
@arden Create a `start.js`:

``` javascript
import micro from 'micro'
import index from './index.js'

micro(index)
```

then:

``` bash
pm2 start.js --name 'xxx'
```

**Comment by timneutkens** [comment]
@amio that's awesome 😄 should document that use case 👍

**Comment by AbeEstrada** [comment]
For future reference, this runs `npm start`:

```bash
pm2 start npm --name "xxx" -- start
```

**Comment by ash0080** [comment]
Not work now, any updates?
I know I can run micro programmatically then use PM2, but can't test it with micro-dev sametime

**Comment by ash0080** [comment]
OK, I got it work

```
// app.js
module.exports = async (req, res) => {
  res.end('welcome to Micro')
}
```
For CLI 

then 

```
// runner.js
const micro = require('micro')
const index = require('./app.js')

const server = micro(index)
server.listen(3000)
```
For PM2
